spring.application.name=mcp
spring.main.web-application-type=none

spring.ai.anthropic.api-key=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

# spring.ai.mcp.client.sse.connections.poet-server.url=http://localhost:8080
spring.ai.mcp.client.streamable-http.connections.poet-server.url=http://localhost:8080

logging.level.io.modelcontextprotocol.client=WARN
logging.level.io.modelcontextprotocol.spec=WARN

# REST-API Credentials für den Einkaufs-Agenten
shopping.api.username=test@test.de
shopping.api.password=password1
