spring.application.name=mcp
spring.main.web-application-type=none

spring.ai.anthropic.api-key=<Füge hier Deinen LLM Key ein>

# spring.ai.mcp.client.sse.connections.shop-server.url=http://localhost:8080
spring.ai.mcp.client.streamable-http.connections.shop-server.url=http://localhost:8080

logging.level.io.modelcontextprotocol.client=WARN
logging.level.io.modelcontextprotocol.spec=WARN

# User Kontext für Einkauf
shopping.api.userid=1
